alarm: custom_cpu_usage_high
   on: system.cpu
lookup: average -30s percentage of user,system,softirq,irq,guest,guest_nice,steal,nice,iowait
 calc: $user + $system + $softirq + $irq + $guest + $guest_nice + $steal + $nice + $iowait
 units: %
 every: 10s
  warn: $this > 80
  crit: $this > 90
  info: Sustained CPU usage is above the expected limit.
    to: sysadmin
